version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    healthcheck:
      test: mysql task_db --user=sword --password='c4ii53SVvoBdLu' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: Wt3bkKEA9J4wSg
      MYSQL_DATABASE: task_db
      MYSQL_USER: sword
      MYSQL_PASSWORD: c4ii53SVvoBdLu
    volumes:
      - mysql-data:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  app:
    build: .
    container_name: sword-health-challenge
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:Wt3bkKEA9J4wSg@db:3306/task_db?allowPublicKeyRetrieval=true
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=f1164d3b-e2ac-4e47-8771-15ce47d84033
      - DEFAULT_MANAGER_EMAIL=manager@email.com
      - DEFAULT_MANAGER_PASSWORD=SWORD_health-2024
      - SALT_ROUNDS=10
    command: yarn dev

volumes:
  mysql-data: 
  rabbitmq-data:
  rabbitmq-log:
