version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    healthcheck:
      test: mysql ${MYSQL_DB} --user=${MYSQL_USER} --password='${MYSQL_PASS}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  app:
    build: .
    container_name: sword-health-challenge
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db:3306/${MYSQL_DB}?allowPublicKeyRetrieval=true
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=${JWT_SECRET}
      - DEFAULT_MANAGER_EMAIL=${DEFAULT_MANAGER_EMAIL}
      - DEFAULT_MANAGER_PASSWORD=${DEFAULT_MANAGER_PASSWORD}
      - SALT_ROUNDS=${SALT_ROUNDS}
    command: yarn dev

volumes:
  mysql-data: 
  rabbitmq-data:
  rabbitmq-log:
